port: "8000"

ttlDocSec: 168  # неделя в часах

db:
  host: "localhost"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

redis:
  hostAndPort: "localhost:6379"
  dbname: 0